# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-25 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('correct_solution_letter', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('time', models.IntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('questions_number', models.IntegerField(default=0)),
                ('instructions', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='blank.png', upload_to=b'')),
                ('question', models.TextField()),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('possible_solution_a', models.CharField(max_length=1000)),
                ('possible_solution_b', models.CharField(blank=True, max_length=1000, null=True)),
                ('possible_solution_c', models.CharField(blank=True, max_length=1000, null=True)),
                ('possible_solution_d', models.CharField(blank=True, max_length=1000, null=True)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
            ],
        ),
        migrations.AddField(
            model_name='correctsolution',
            name='exam',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam'),
        ),
    ]
