# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-19 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='description',
            new_name='instructions',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='category',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='date',
        ),
        migrations.AddField(
            model_name='exam',
            name='questions_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
