# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-25 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='date',
            new_name='date_created',
        ),
    ]
