# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-20 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_auto_20201019_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorrectSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('correct_solution', models.CharField(max_length=2)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('question', models.TextField()),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
            ],
        ),
        migrations.CreateModel(
            name='SolutionsText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(default=0)),
                ('possible_solution_a', models.CharField(max_length=200)),
                ('possible_solution_b', models.CharField(max_length=200)),
                ('possible_solution_c', models.CharField(max_length=200)),
                ('possible_solution_d', models.CharField(max_length=200)),
                ('exam', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.Exam')),
            ],
        ),
    ]
