# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-25 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20201025_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
