# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-21 02:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20201021_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='solutionstext',
            name='possible_solution_a',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='solutionstext',
            name='possible_solution_b',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='solutionstext',
            name='possible_solution_c',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='solutionstext',
            name='possible_solution_d',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
