# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-25 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20201025_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
