# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20201025_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctsolution',
            name='correct_solution_letter',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='exams.SolutionsText'),
        ),
    ]
