# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-10-27 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_auto_20201027_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctsolution',
            name='correct_solution_letter',
            field=models.CharField(max_length=1),
        ),
    ]
