# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-01 15:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('id_number', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='companies.Company')),
            ],
        ),
    ]
