# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-11-01 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('staff_name', models.CharField(max_length=200)),
                ('staff_number', models.CharField(max_length=200)),
            ],
        ),
    ]
